### ISSUE TITLE
Interned symbols in ASDF file

### ISSUE THREAD

**Issue by phoe** [turtle-bazon/cl-maxminddb#1]
https://github.com/turtle-bazon/cl-maxminddb/blob/a66e6ab7167d63f30c1db024725f6f932cf43acb/cl-maxminddb.asd#L9-L15

I suggest using `#:babel` or `"babel"` instead of `babel` et al in order to avoid polluting the ASDF namespace with newly interned symbols.

**Comment by turtle-bazon** [comment]
fixed in https://github.com/turtle-bazon/cl-maxminddb/commit/4971ee86ade9afd8d81cb56d2ba5fe2e2645ff6b

**Comment by phoe** [comment]
Thanks!
