### ISSUE TITLE
Camel-case notation is ignored

### ISSUE THREAD

**Issue by phoe** [turtle-bazon/cl-maxminddb#2]
https://github.com/turtle-bazon/cl-maxminddb/blob/a66e6ab7167d63f30c1db024725f6f932cf43acb/src/maxminddb.lisp#L10

`MaxMindDatabaseMetadata` is equivalent to `maxminddatabasemetadata` under standard read-case settings of the Lisp reader. I suggest using standard Lisp kebab-case notation instead and change that to `maxmind-database-metadata`

**Comment by turtle-bazon** [comment]
fixed in 0.0.1.1
